### ISSUE TITLE
Please specify license

### ISSUE THREAD

**Issue by mih** [Brainhack-Proceedings-2015/Hernandez-AMX-DogVest#1]
I cannot see a license for source code, STL design files, or the article itself. Please specify an appropriate license for each component to facilitate derivative works. Relevant licenses would be CC0 for STL files and article, and MIT or BSD license for the program source code.

**Comment by nekrum** [comment]
Hi,
Sorry for the delay, we add a License.txt in scripts folder, and CCO in README.md in repository
Thank you for the suggestion, are they the adequate licenses?

**Comment by mih** [comment]
Thanks, I think this is good.
