### ISSUE TITLE
Please include description of principle features and implementation

### ISSUE THREAD

**Issue by mih** [Brainhack-Proceedings-2015/Hernandez-AMX-DogVest#2]
The report talks about the device's capability to capture heart rate and tail movement. However, no description is given on how this information is captured. The only hint is given in the table with the component list. For someone not familiar with the arduino platform or with those components it would be very helpful to give a compact description on what role each component has, and how they all work together.

For someone wanting to build such a device it would also be very helpful to indicate with features provided by each component were critical. I assume that there are alternatives that would work equally well and may be better accessible/available elsewhere or in the future.

**Comment by nekrum** [comment]
In the Pull Request  #7 line 233 the Arduino and EKG-EMG-shield features are described, also line 325 add more details to implementation of the devices.
Thanks for the suggestions

**Comment by mih** [comment]
Thanks for the change!
