### ISSUE TITLE
Please give indication on the nature of the data output

### ISSUE THREAD

**Issue by mih** [Brainhack-Proceedings-2015/Hernandez-AMX-DogVest#3]
The actual arduino code is relatively compact and naturally seems to be focused on data capture. Please give some indication on the nature of the output data of the device. How many/which sensor outputs, sampling rate, data format (text/binary), and maybe how it can/must be further processed. Essentially all  information that is necessary to produce something like the plots in the manuscript.

**Comment by nekrum** [comment]
Pull Request #7 line 267, describe the nature of the data output and some details of the data format.
Thank you for the feedback.

**Comment by mih** [comment]
Thanks!
